spring:
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/tld_local?serverTimezone=Asia/Seoul
    username: root
    password: sqisoft123@
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      connection-timeout: 30000
      validation-timeout: 3000
      connection-test-query: select 1
  jpa:
    hibernate:
      query:
        in_clause_parameter_padding: true
        plan_cache_max_size: 256
        plan_parameter_metadata_max_size: 16
      format_sql: true
      default_batch_fetch_size: 100
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      jakarta:
        persistence:
          sharedCache:
            mode: UNSPECIFIED
    open-in-view: false

logging:
  level:
    com.example.test: debug

file:
  upload:
    home: "D:/temp"